spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_manager
    username: root
    password: 1234@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  messages:
    basename: application, errors

  #jsp 설정
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

logging:
  level:
    org.hibernate.SQL: debug
server:
  servlet:
    session:
      tracking-modes: cookie
